CREATE DATABASE SQJ;
USE SQJ;
CREATE TABLE Press(
PNo CHAR(16) PRIMARY KEY,
PName CHAR(20) UNIQUE,
PCode CHAR(6) CHECK(PCode LIKE'[0-9][0-9][0-9][0-9][0-9][0-9]'),
PAddr CHAR(30),
Phone CHAR(16) CHECK(LENGTH(Phone)<=15),
EMail CHAR(26) CHECK(0<LOCATE('@',EMail)),
HPage CHAR(25));
